/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Familia
 */

import model.SecondHandShop;
import model.User;
import model.Category;
import model.Product;
import model.Address;

public class SecondHandShopFrom extends javax.swing.JFrame {

    /**
     * Creates new form SecondHandShopFrom
     */
    
    SecondHandShop shop;
    
    public SecondHandShopFrom() {
        shop = new SecondHandShop();
        shop.addUser("Katy", "Purry", "TheRealKaty@hotmail.com", 
                "696969", "Calle MiamiStreet", 45, "Miami","685FE4", "GringoLandia" );
        shop.addUser("Jesus", "Larez", "jesuslarez@ulpgc.es", 
                "jesus", "Calle Felo Monzon", 23, "Las Palmas","35015", "Spain" );
        shop.addUser("Luis", "Galindo", "luisgalindo@ulpgc.es", 
                "luis", "Calle Practicante", 13, "Las Palmas","35017", "Spain" );
        shop.addUser("Esther", "Gonzalez", "esthergonzalez@ulpgc.es", 
                "essher", "Calle Guanarteme", 26, "Las Palmas","35011", "Spain" );
        shop.addUser("Katty", "Hernandez", "kattyhernandez@ulpgc.es", 
                "katty", "Calle Mesa y Lopez", 5, "Las Palmas","35010", "Spain" );
        shop.addUser("Shraddha", "Sharma", "shraddhasharma@ulpgc.es", 
                "shraddha", "Calle King Crescent", 24, "Sheffield","SH24 6QR", "United Kingdow" );
        shop.addUser("Nayara", "Aguilar", "nayaraaguilar@ulpgc.es", 
                "nayara", "Calle Venezuela", 19, "Las Palmas","35009", "Spain" );
        
        //CATEGORIAS
        
        shop.addCategory("Libros" );
        shop.addCategory("Ropa" );
        shop.addCategory("Mujer", Ropa );
        shop.addCategory("Hombre" , Ropa );
        shop.addCategory("Musica" );
        shop.addCategory("Coches" );
        shop.addCategory("Electronica" );
        shop.addCategory("PC" ,Electronica );
        shop.addCategory("Electrodomesticos", Electronica);
        shop.addCategory("Muebles" );
        shop.addCategory("Coches" );
        shop.addCategory("Belleza" );
        
        shop.userList.get(0).offerProduct(Cosa, 25.5 , "something", "imagen", Libros);
        initComponents();
    }

    /**
     * This method is called from within the constructor to  the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        UserLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        passField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        passwordLabel.setText("Password");

        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        UserLabel.setText("User");

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        passField.setText("jPasld1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginButton)
                    .addComponent(emailField)
                    .addComponent(passField, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addGap(304, 304, 304))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(loginButton)
                .addGap(81, 81, 81))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        if(shop.logIn(emailField.getText(), passField.getText())){
            new CheckWindow().setVisible(true);
        }else{
            emailField.setText("");
            passField.setText("");
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecondHandShopFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecondHandShopFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecondHandShopFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecondHandShopFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecondHandShopFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UserLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel passwordLabel;
    // End of variables declaration//GEN-END:variables
}
